In [1]:
import numpy as np
import matplotlib as plt

In [2]:
import matplotlib.pylab as plt

In [3]:
##Scalar-array and array-array operations

In [4]:
#let's make a 2*3 array
A=np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

Note that arthimetic operations works element wise

In [5]:
2*A

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [6]:
B=np.array([[7,9,2],[3,1, 1]])

In [7]:
B-1

array([[6, 8, 1],
       [2, 0, 0]])

In [8]:
B-A

array([[ 6,  7, -1],
       [-1, -4, -5]])

In [9]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
B

array([[7, 9, 2],
       [3, 1, 1]])

In [11]:
#zip function
A=[2,4]
B=[[2,3], [4,5]]
list(zip(A,B))

[(2, [2, 3]), (4, [4, 5])]

In [12]:
list(zip(*B))

[(2, 4), (3, 5)]

In [13]:
A=[[2,4],[4,5]]
B=[[2,3], [4,5]]
zip(A,B)


In [14]:
list(zip(A,B))

[([2, 4], [2, 3]), ([4, 5], [4, 5])]

In [15]:
A=[[1,2,3], [4,5,6]]
B=[[2,4],
   [3,5],
   [1,3]]

In [23]:
c=list(zip(*B))
c

[(2, 3, 1), (4, 5, 3)]

In [25]:
list(zip(A,c))

[([1, 2, 3], (2, 3, 1)), ([4, 5, 6], (4, 5, 3))]

In [26]:
A=np.array(A)
B=np.array(B)
np.dot(A,B)

array([[11, 23],
       [29, 59]])

In [27]:
A*B


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [28]:
#to convert array to matrix and use arthmetic operations
A=np.matrix(A)

In [29]:
B=np.matrix(B)

In [30]:
A*B

matrix([[11, 23],
        [29, 59]])

In [31]:
a =np.ones(4)

In [32]:
a

array([1., 1., 1., 1.])

In [33]:
a=np.matrix(a)

In [34]:
a

matrix([[1., 1., 1., 1.]])

In [35]:
a.T

matrix([[1.],
        [1.],
        [1.],
        [1.]])

In [36]:
b=np.ones(4)

In [37]:
b

array([1., 1., 1., 1.])

In [38]:
b.T

array([1., 1., 1., 1.])

In [39]:
b.T

array([1., 1., 1., 1.])

In [43]:
a=np.array[[1,2],[4,5]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [41]:
a.T

AttributeError: 'tuple' object has no attribute 'T'

In [44]:
A=np.array(A)

In [45]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
D=np.random.randint(0,2,(10,10))

In [48]:
D

array([[1, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 1, 1, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 1, 1, 0, 1, 1, 0, 0, 0]])

In [49]:
a=np.ones(10)

In [50]:
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
a=np.matrix(a)

In [53]:
a

matrix([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [54]:
a.T

matrix([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [55]:
a=a.T

In [56]:
a

matrix([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [57]:
D=np.matrix(D)

In [58]:
D

matrix([[1, 0, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 0, 0, 1, 0, 0, 0, 0, 0, 1],
        [1, 0, 1, 0, 1, 0, 0, 1, 1, 1],
        [0, 0, 1, 1, 0, 1, 0, 1, 0, 1],
        [0, 0, 0, 1, 0, 0, 0, 1, 1, 1],
        [1, 0, 0, 0, 1, 0, 1, 1, 0, 0],
        [1, 0, 0, 0, 1, 1, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 0, 0, 1, 1, 0, 0, 0],
        [1, 0, 1, 1, 0, 1, 1, 0, 0, 0]])

In [59]:
D*a

matrix([[6.],
        [3.],
        [6.],
        [5.],
        [4.],
        [4.],
        [4.],
        [3.],
        [5.],
        [5.]])